import type { Metadata } from "next";
import localFont from "next/font/local";
import { NavbarComponent } from "./Components/layout/navbar/NavbarComponent";
import { SidebarComponent } from "./Components/layout/sidebar/SidebarComponent";
import StoreProvider from "./StoreProvider";
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
           <StoreProvider>
          <header>
            <NavbarComponent />
          </header>
          <aside className="flex">
            <SidebarComponent />
            <div className="flex h-screen bg-[#fdfdfd]">
              {children}
              </div>
          </aside>
        </StoreProvider>
      </body>
    </html>
  );
}
