import type { Metadata } from "next";
import StoreProvider from "../StoreProvider";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <header></header>
          <aside className="flex">
            <div className="flex h-screen bg-[#fdfdfd]">{children}</div>
          </aside>
        </StoreProvider>
      </body>
    </html>
  );
}
