import type { Metadata } from "next";
import localFont from "next/font/local";

// import { SidebarComponent } from "@/app/Components/layout/sidebar/SidebarComponent";
// import { NavbarComponent } from "@/app/Components/layout/navbar/NavbarComponent";
import StoreProvider from "@/app/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <header>{/* <NavbarComponent /> */}</header>
          <aside className="flex">
            {/* <SidebarComponent /> */}
            <div className="flex h-screen bg-[#fdfdfd]">{children}</div>
          </aside>
        </StoreProvider>
      </body>
    </html>
  );
}
